#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.1 on Sat Apr 15 16:56:36 2017
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        wx.Frame.__init__(self, *args, **kwds)
        self.label_1 = wx.StaticText(self, wx.ID_ANY, "                                                                                         SPAM", style=wx.ALIGN_RIGHT)
        self.label_2 = wx.StaticText(self, wx.ID_ANY, "DETECTOR", style=wx.ALIGN_LEFT)
        #self.static_line_1 = wx.StaticLine(self, wx.ID_ANY, style=wx.EXPAND)
        #self.static_line_2 = wx.StaticLine(self, wx.ID_ANY, style=wx.EXPAND)
        self.label_3 = wx.StaticText(self, wx.ID_ANY, "Filename           :")
        self.text_ctrl_1 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.button_1 = wx.Button(self, wx.ID_ANY, "Check")
        self.button_2 = wx.Button(self, wx.ID_ANY, "")
        self.label_4 = wx.StaticText(self, wx.ID_ANY, "File content     :")
        self.button_3 = wx.Button(self, wx.ID_ANY, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.checking, self.button_1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame_1")
        self.SetSize((640, 320))
        self.button_2.SetMinSize((82, 34))
        self.button_3.SetMinSize((480, 100))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.GridSizer(5, 2, 1, 1)
        grid_sizer_1.Add(self.label_1, 0, 0, 0)
        grid_sizer_1.Add(self.label_2, 0, 0, 0)
        #grid_sizer_1.Add(self.static_line_1, 0, 0, 0)
        #grid_sizer_1.Add(self.static_line_2, 0, 0, 0)
        grid_sizer_1.Add(self.label_3, 0, 0, 0)
        grid_sizer_1.Add(self.text_ctrl_1, 0, 0, 0)
        grid_sizer_1.Add(self.button_1, 0, 0, 0)
        grid_sizer_1.Add(self.button_2, 0, 0, 0)
        grid_sizer_1.Add(self.label_4, 0, 0, 0)
        grid_sizer_1.Add(self.button_3, 0, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, 0, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def checking(self, event):  # wxGlade: MyFrame.<event_handler>
        grad=0.512058826033 #Our gradient value as calculated with the help of logistic regression
        name=self.text_ctrl_1.Value
	try:
		f=open(name,"r")
	except IOError as e:
		self.button_2.SetLabel("No such file")
		self.button_3.SetLabel("File does not exist")
	g=open("nocspamw.txt","r")
	fcontent=f.read();
	gcontent=g.read();
	fwords=fcontent.split()
	gwords=gcontent.split()
	twc=0.0
	swc=0.0
	for i in fwords:
		twc=twc+1
	for i in fwords:
		for j in gwords:
			if i==j:
				swc=swc+1
	prob=float(swc/twc)
	#print "Total word count= ",twc
	#print "Spam word count= ",swc
	#print "Probability obtained= ",prob
	if prob>grad:
		self.button_2.SetLabel("Spam")
	else:
		self.button_2.SetLabel("Not Spam")
	self.button_3.SetLabel(fcontent)
        event.Skip()

# end of class MyFrame
if __name__=="__main__":
	app=wx.App()
	MyFrame(None,-1,"").Show()
	app.MainLoop()
