#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.1 on Fri Apr 14 17:40:49 2017
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        wx.Frame.__init__(self, *args, **kwds)
        self.label_1 = wx.StaticText(self, wx.ID_ANY, "        SPAM DETECTOR      ", style=wx.ALIGN_CENTER)
        self.static_line_1 = wx.StaticLine(self, wx.ID_ANY, style=wx.EXPAND)
        self.label_2 = wx.StaticText(self, wx.ID_ANY, "Filename    :")
        self.text_ctrl_1 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.button_1 = wx.Button(self, wx.ID_ANY, "Check")
        self.button_2 = wx.Button(self, wx.ID_ANY, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.opening, self.button_1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame_1")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(self.label_1, 0, 0, 0)
        sizer_3.Add(self.static_line_1, 0, 0, 0)
        sizer_4.Add(self.label_2, 0, 0, 0)
        sizer_4.Add(self.text_ctrl_1, 0, 0, 0)
        sizer_3.Add(sizer_4, 1, 0, 0)
        sizer_5.Add(self.button_1, 0, 0, 0)
        sizer_5.Add(self.button_2, 0, 0, 0)
        sizer_3.Add(sizer_5, 1, 0, 0)
        sizer_1.Add(sizer_3, 1, 0, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def opening(self, event):  # wxGlade: MyFrame.<event_handler>
	grad=0.512058826033 #Our gradient value as calculated with the help of logistic regression
        name=self.text_ctrl_1.Value
	try:
		f=open(name,"r")
	except IOError as e:
		self.button_2.SetLabel("No such file")
	g=open("nocspamw.txt","r")
	fcontent=f.read();
	gcontent=g.read();
	fwords=fcontent.split()
	gwords=gcontent.split()
	twc=0.0
	swc=0.0
	for i in fwords:
		twc=twc+1
	for i in fwords:
		for j in gwords:
			if i==j:
				swc=swc+1
	prob=float(swc/twc)
	#print "Total word count= ",twc
	#print "Spam word count= ",swc
	#print "Probability obtained= ",prob
	if prob>grad:
		self.button_2.SetLabel("Spam")
	else:
		self.button_2.SetLabel("Not Spam")
        event.Skip()

# end of class MyFrame

if __name__=="__main__":
	app=wx.App()
	MyFrame(None,-1,"").Show()
	app.MainLoop()
